version: '3.8'

services:
  db:
    image: postgres:13.2
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DATABASE}
    container_name: ppw_db
    volumes:
      - ./db:/var/lib/postgresql/data

  ppw:
    build: .
    container_name: ppw_backend
    command: yarn dev
    volumes:
      - ./:/backend
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
